export const navigation = [
  {
    name: "qr",
    link: "/qr",
    img: "/assets/qr/design/desktop-design.jpg",
    description: "QR code generator",
  },
  {
    name: "interactive rating",
    link: "interactive-rating",
    img: "/assets/interactive-rating-component-main/design/active-states.jpg",
    description: "interactive rating",
  },
  {
    name: "shopping-cart",
    link: "/shopping-cart",
    img: "/assets/shopping-cart.jpeg",
    description: "shopping cart",
  },
  {
    name: "product-preview",
    link: "/product-preview",
    img: "/assets/product-preview-card-component-main/product-preview-card-component-main/design/desktop-design.jpg",
    description: "product preview",
  },
  {
    name: "nft",
    link: "/nft",
    img: "/assets/nft-preview-card-component-main/design/desktop-design.jpg",
    description: "nft",
  },
  {
    name: "rock-paper-scissors",
    link: "/rock-paper-scissors",
    img: "/assets/rock-paper-scissors/design/desktop-preview.jpg",
    description: "rock-paper-scissors",
  },
  {
    name: "profile-card",
    link: "/profile-card",
    img: "/assets/profile-card-component-main/design/desktop-design.jpg",
    description: "profile-card",
  },
  {
    name: "advice",
    link: "advice",
    img: "/assets/advice-generator-app-main/design/active-states.jpg",
    description: "advice",
  },
  {
    name: "expenses-chart",
    link: "expenses-chart",
    img: "/assets/expenses-chart/design/active-states.jpg",
    description: "expenses-chart",
  },
  {
    name: "password-generator",
    link: "password-generator",
    img: "/assets/password-generator.jpg",
    status: "in progress",
    description: "password-generator",
  },
  {
    name: "news homepage",
    link: "news",
    img: "/assets/news/design/active-states.jpg",
    description: "news homepage",
    status: "in progress",
  },
  {
    name: "order-summary",
    link: "/order-summary",
    img: "/assets/order-summary/design/desktop-design.jpg",
    description: "Order summary",
  },
  {
    name: "hydrate",
    link: "/hydrate",
    img: "/assets/hydrate.jpeg",
    description: "Hydrate",
    status: "old project",
  },

  {
    name: "four card feature",
    link: "four-card-feature",
    img: "/assets/four-card-feature-section-master/design/desktop-design.jpg",
    description: "four card feature",
  },
  {
    name: "clock",
    link: "clock",
    img: "/assets/clock.png",
    description: "clock",
    status: "old project",
  },
  {
    name: "login",
    link: "login",
    img: "/assets/login.png",
    description: "login",
  },
  // {
  //     name: "dictionary",
  //     link: "dictionary",
  //     img: "/assets/dictionary/preview.jpg",
  //     description: "dictionary",
  //     status: "in progress",
  // },
  // {
  //     name: "comments",
  //     link: "comments",
  //     img: "/assets/comments/design/desktop-design.jpg",
  //     description: "comments",
  //     status: "in progress",
  // },
  // {
  //     name: "ecommerce",
  //     link: "ecommerce",
  //     img: "/assets/ecommerce-product-page-main/ecommerce-product-page-main/design/desktop-design.jpg",
  //     description: "ecommerce",
  //     status: "in progress",
  // },

  // {
  //     name: "url-shortening",
  //     link: "url-shortening",
  //     img: "/assets/url-shortening-api-master/url-shortening-api-master/design/desktop-design.jpg",
  //     description: "url-shortening",
  // }
];
